services:
  app:
    build: .
    env_file: .env
    container_name: "socket-chat"
    entrypoint: "/tmp/entrypoint/docker-entrypoint.sh"
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${HOST}:${PORT}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./src:/workspace
      - /workspace/public/assets  # ignore build assets
      - ./entrypoint:/tmp/entrypoint/
    depends_on:
      - redis
  redis:
    image: redis:8.0.1-alpine
    container_name: "redis-limiter"
    restart: unless-stopped
