[tool.black]
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120

src_paths = ["src"]

[tool.bandit]
exclude_dirs = ['.venv']

[tool.pyright]
pythonVersion = "3.13"
pythonPlatform = "Linux"
venv = ".venv"
include = ["src"]
exclude = ["**/__pycache__"]